# Generated by Django 5.1.1 on 2024-09-15 15:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_record_description_record_price_alter_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.DeleteModel(
            name='record',
        ),
    ]
